spring:
  application:
    name: rmq-stream-source
  cloud:
    function:
      definition: supplyFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          supplyFoo-out-0: output
      bindings:
        output:
          destination: foo-stream
  # RabbitMQ configurations for streams
      rabbit:
        bindings:
          output:
            producer:
              declare-exchange: false
              producer-type: stream-async
              super-stream: true
  rabbitmq:
    stream:
      host: localhost
      port: 5552
      username: guest
      password: guest
