spring:
  application:
    name: rmq-stream-source
  cloud:
    function:
      definition: supplyFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          supplyFoo-out-0: output
      # Spring CLoud Stream configurations for bindings set by Data Flow
      # bindings:
      #   output:
      #     destination: foo-stream.foo-source
      #     producer:
      #       requiredGroups: foo-stream
  # RabbitMQ configurations for RabbitMQ stream API
  #     rabbit:
  #       bindings:
  #         output:
  #           producer:
  #             declare-exchange: false
  #             producer-type: stream-async
  #             super-stream: true
  # rabbitmq:
  #   stream:
  #     host: localhost
  #     port: 5552
  #     username: guest
  #     password: guest
