spring:
  application:
    name: rmq-stream-sink
  cloud:
    function:
      definition: storeFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          storeFoo-in-0: input
      bindings:
        input:
          destination: foo-stream
          group: foo-stream-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
  # RabbitMQ configurations for streams
  #     rabbit:
  #       bindings:
  #         storeFoo-in-0:
  #           consumer:
  #             declare-exchange: false
  #             exchange-type: topic
  #             container-type: stream
  #             super-stream: true
  # rabbitmq:
  #   listener:
  #     type: stream
  #   stream:
  #     host: localhost
  #     port: 5552
  #     username: guest
  #     password: guest
